# Generated by Django 5.2.6 on 2025-09-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='No bio yet', max_length=160),
        ),
    ]
